export const rentHouses = [
  {
    id: 1,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/12.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 1x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "1 xonalik",
      "33 kv/m  | 38 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
  {
    id: 2,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 1x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "1 xonalik",
      "41 kv/m | 45 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
  {
    id: 3,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/10.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 2x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "2 xonalik",
      "45 kv/m | 50 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
  {
    id: 4,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/2.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 2x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "2 xonalik",
      "55 kv/m  | 62 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
  {
    id: 5,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/3.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 3x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "3 xonalik",
      "58 kv/m  | 65 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
  {
    id: 6,
    type: "Uylar",
    mainImage: "https://yaqeenuz.files.wordpress.com/2024/04/4.jpg",
    moreImages: [
      "https://yaqeenuz.files.wordpress.com/2024/04/1.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/6.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/7.jpg",
      "https://yaqeenuz.files.wordpress.com/2024/04/8.jpg",
    ],
    name: "Orient 3x",
    address: "2-Kichik daha, Andijon .Sh",
    price: 0,
    details: [
      "3 xonalik",
      "76 kv/m | 100 kv/m",
      "Uylar karobka holatda",
      "Joylashuv o'rni juda ham yahshi",
      "Atrof muhit sokin",
    ],
    description:
      "Uylar 1 etajdan 11 hamda 12 etajgacha joylashgan hamda bino 7 blokdan iboratdur A, B, C, D1, D2 va E , F bloklar hisoblanadi",
  },
];
